_format_version: "3.0"
_transform: true

services:
  - name: shortlink-manager-service
    url: http://10.200.0.40:8080
    routes:
      - name: shortlink-manager-service-route
        paths:
          - /sms
        methods:
          - GET
          - POST
          - DELETE
        strip_path: true

  - name: redirect-service
    url: http://10.200.0.60:8082
    routes:
      - name: redirect-service-route
        paths:
          - /rs
        methods:
          - GET
        strip_path: true

  - name: short-link-metrics-service
    url: http://10.200.0.90:8083
    routes:
      - name: short-link-metrics-service-route
        paths:
          - /smts
        methods:
          - GET
        strip_path: true
